# PVC for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mern-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# PVC for Frontend
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
  namespace: mern-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi


---
# Backend Deployment with Init Container and Sidecar
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-stack
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          until nc -z mongodb-service 27017; do
            echo "Initializing Backend...."
            sleep 10
          done
          echo "Backend is ready!"
      containers:
      - name: backend
        image: ismailza/mern-stack-app-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASS
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: APP_MODE
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: log-volume
          mountPath: /var/log
      - name: sidecar
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          touch /var/log/backend.log
          tail -f /var/log/backend.log
        volumeMounts:
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: log-volume
        emptyDir: {}

---
# Frontend Deployment with Rolling Update Strategy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-stack
  labels:
    app: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ismailza/mern-stack-app-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: PORT
          value: "5173"
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
          volumeMounts:
          - name: frontend-storage
            mountPath: /usr/share/nginx/html
        volumes:
      - name: frontend-storage
        persistentVolumeClaim:
          claimName: frontend-pvc

---
# MongoDB Deployment with Persistence
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mern-stack
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc